name: Pylint
on: [pull_request]

jobs:
  default:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Run "make lint" in docker container
        env: 
          GH_ACTIONS_SUITE: "lint"
        run: ci/launch-docker.sh 
